# Generated by Django 2.0.2 on 2018-04-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phystunion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
