# Generated by Django 2.0.2 on 2018-04-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phystunion', '0002_auto_20180409_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
